services:
  order-service:
    image: 286885992381.dkr.ecr.us-east-1.amazonaws.com/order-service-go:latest
    container_name: order-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: [
        # "./wait-for-it.sh",
        # "mysql:3306",
        # "--",
        # "./wait-for-it.sh",
        # "rabbitmq:5672",
        # "--timeout=60",
        # "--",
        "./api",
      ]

  invoice-service:
    image: 286885992381.dkr.ecr.us-east-1.amazonaws.com/invoice-service-js:latest
    container_name: invoice-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    command:
      [
        "./wait-for-it.sh",
        "mysql:3306",
        "--",
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--timeout=60",
        "--",
        "node",
        "index.js",
      ]

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: devops
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
