services:
  order-service:
    image: 286885992381.dkr.ecr.us-east-1.amazonaws.com/order-service-go:latest
    container_name: order-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["./api"]
