name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
      - run: |
          cd invoice-service-js 
          npm install

      - name: Generate tag
        id: generate_tag
        # Boa prática usar os 7 primeiro caracteres do SHA do commit como tag da imagem
        # Também é boa prática jogar a variável de ambiente para o output do step
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./invoice-service-js/.
          push: true
          # Pushing duas tags por boa prática, a tag do commit e latest
          tags: xanderdn/invoice-service-js:${{ steps.generate_tag.outputs.sha }},xanderdn/invoice-service-js:latest
